services:
  crond:
    build:
      context: https://github.com/yushiyangk/ddns-cloudflare.git#docker
      dockerfile: docker/build/Dockerfile
      pull: true
    image: ddns-cloudflare
    env_file:
    - .env
    init: true
    tty: true
    stdin_open: true
    cap_drop:
    - all
    cap_add:
    - CAP_SETGID
    security_opt:
    - no-new-privileges
    read_only: true
    volumes:
    - type: tmpfs
      target: /etc/crontabs
      tmpfs:
        mode: 0755
    - type: tmpfs
      target: /etc/ssmtp
      tmpfs:
        mode: 0755
    - type: tmpfs
      target: /var/spool/cron
      tmpfs:
        mode: 0755
    - type: bind
      source: config
      target: /etc/opt/ddns-cloudflare
      read_only: true
    - type: bind
      source: ssmtp.conf
      target: /etc/ssmtp/ssmtp.conf
      read_only: true
    networks:
    - network
    command: -qq

networks:
  network:
    driver: bridge
